### ISSUE TITLE
#BUG# showThumb 不能过滤非图片类附件

### ISSUE THREAD

**Issue by xw-fu** [loozx/lpisme#7]
> function showThumb(){...}  Line: 60

 // 如果附件的类型为未知或其他格式， $this的 attachment里的属性isImage是存在的。
//  所以这里应该修改为： isset($attach->isImage) && $attach->isImage == 1

```
if (isset($attach->isImage)){}
```

**Comment by chakhsu** [comment]
好的，谢谢！
